# https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually

name: template-python-miniconda-notebook
channels:
  - conda-forge
dependencies:
  # https://anaconda.org/conda-forge/python?version=3.10.14
  - python=3.10.14
  # https://github.com/python/cpython/blob/v3.10.14/Lib/ensurepip/__init__.py#L15
  - pip=23.0.1
  # https://anaconda.org/conda-forge/jupyterlab?version=4.1.5
  - jupyterlab=4.1.5
